[package]
name = "ldog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gemini = "0.0.5"
log = "0.4.17"

rand = "0.8.3"
